YorsGate/YorsGate/urls.py
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

from YorsGate import settings
from game.views import *
from users.views import *

urlpatterns = [
    path('admin/', admin.site.urls),
    path('game/', include('game.urls')),
    path('', include('users.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

YorsGate/game/urls.py
from django.urls import path, re_path

from .views import *

app_name = 'game'

urlpatterns = [
    path('merchant/', merchant, name='order_page'),
    path('warehouse/', warehouse_append, name='warehouse'),
    path('shop/', shop, name='shop')
]

YorsGate/users/urls.py
from django.urls import path, re_path, include

from .views import *

app_name = 'users'

urlpatterns = [
    path('', main_page, name='home'),
    path('', include('django.contrib.auth.urls')),
    path('register/', register, name='register')
]

YorsGate/game/models.py
from random import randint

from django.db import models
from django.contrib.auth.models import User


class Player(models.Model):
    nickname = models.TextField(max_length=16)
    money = models.IntegerField(default=0)
    warehouse_capacity = models.IntegerField(default=100)
    reputation = models.IntegerField(default=50)
    user = models.OneToOneField(User,
                                on_delete=models.CASCADE)

    def __str__(self):
        return f"Name: {self.nickname}| " \
               f"Money: {self.money}| " \
               f"Warehouse: {self.warehouse_capacity}| " \
               f"Reputation {self.reputation}"


class Ware(models.Model):
    product_name = models.TextField()
    price = models.IntegerField(default=0)
    time_of_sale = models.TimeField()
    product_volume = models.IntegerField()

    def __str__(self):
        return f"Name: {self.product_name}|" \
               f" Price: {self.price}|" \
               f" Volume: {self.product_volume}|" \
               f" Time of sale: {self.time_of_sale}|"


class Warehouse(models.Model):
    player = models.ForeignKey(Player, on_delete=models.CASCADE)
    ware = models.ForeignKey(Ware, on_delete=models.CASCADE)
    count = models.IntegerField(default=1)

    def __str__(self):
        return f"Merchant: {self.player.nickname}|  Ware: {self.ware.product_name}"

YorsGate/users/models.py
from django.db import models

YorsGate/game/forms.py
from django import forms


class CharForm(forms.Form):
    nickname = forms.CharField(max_length=14, min_length=3)


class MessageForm(forms.Form):
    message = forms.CharField(max_length=90)

YorsGate/users/forms.py
from django import forms
from django.contrib.auth import password_validation
from django.contrib.auth.forms import UsernameField, UserCreationForm
from django.contrib.auth.models import User
from django.contrib.auth.validators import UnicodeUsernameValidator
from django.core.exceptions import ValidationError
from django.db import models
from django.utils.translation import gettext_lazy as _


class RegistrationForm(UserCreationForm):
    def __init__(self, *args, **kwargs):
        super(RegistrationForm, self).__init__(*args, **kwargs)

        for field_name in ['username', 'password1', 'password2']:
            self.fields[field_name].help_text = None

YorsGate/game/views.py
from random import random
from typing import Dict, Any

from django.contrib.auth.decorators import login_required
from django.contrib.auth.models import User
from django.db.models import F
from django.http import HttpRequest, HttpResponse, JsonResponse
from django.shortcuts import render, redirect
from .models import *
from json import loads

from .models import Ware


# Views == Controller
@login_required
def merchant(request):
    if not Player.objects.filter(id=request.user.id).exists():
        Player.objects.create(nickname=request.user.username,
                              user_id=request.user.id)

    player = Player.objects.get(id=request.user.id)
    wares = Ware.objects.all()

    context = {
        "title": 'Порт Йорсу',
        "user_id": request.user.id,
        "player": player,
        "wares": wares,
    }

    return render(request, 'game/merchant.html', context=context)


@login_required()
def warehouse_append(request):
    player = Player.objects.get(id=request.user.id)
    player_wares = Warehouse.objects.filter(player_id=request.user.id)

    if request.method == "POST":
        wares = loads(request.body)
        order_sum = 0
        for ware in wares:
            if ware['count'] > 0:
                if len(player_wares.filter(ware_id=ware['ware'])) > 0:
                    player_wares.filter(ware_id=ware['ware']).update(count=F('count') + ware['count'])
                    print(player_wares.get(ware_id=ware['ware']).count)
                else:
                    player_wares.create(player_id=request.user.id, ware_id=ware['ware'], count=ware['count'])
                order_sum += ware['price']

        player.money -= order_sum
        player.save()

    order_volume = 0
    max_capacity = 100 + (player.reputation / 10) * 4

    for ware in player_wares:
        order_volume += ware.ware.product_volume

    player.warehouse_capacity = max_capacity - order_volume
    player.save()

    context = {
        'title': 'Склад',
        "player": player,
        'wares': player_wares,
        'wares_volume': order_volume,
        'capacity': max_capacity
    }

    return render(request, 'game/warehouse.html', context=context)


@login_required()
def shop(request):
    player = Player.objects.get(id=request.user.id)
    player_wares = Warehouse.objects.filter(player_id=request.user.id).order_by('ware_id')

    if request.method == "POST":
        sell_wares = loads(request.body)
        sell_sum = 0
        for ware in sell_wares:
            sell_ware = Warehouse.objects.get(player_id=request.user.id, ware_id=ware['id'])
            if ware['count'] < sell_ware.count:
                sell_sum += ware['count'] * sell_ware.ware.price
                sell_ware.count -= ware['count']
                sell_ware.save()
            else:
                sell_sum += sell_ware.count * sell_ware.ware.price
                sell_ware.delete()

            player.money += sell_sum + (player.reputation - 50)

    context = {
        'title': 'Ваш магазин',
        'player': player,
        'player_wares': player_wares,
    }

    return render(request, 'game/shop.html', context=context)

YorsGate/users/views.py
from django.contrib.auth import login
from django.contrib.auth.forms import UserCreationForm
from django.http import HttpResponse
from django.shortcuts import render, redirect
from .forms import RegistrationForm as reg_form
from .models import *


# Контроллер головної сторінки
def main_page(request):
    context = {'title': 'YorsGate'}
    return render(request, 'users/index.html', context=context)


# Контроллер для ідентифікації і реєстрації користувачів
def register(request):
    # Якщо форма не була заповнена відмальовуємо її інакше проводимо валідацію
    if request.method != 'POST':
        form = reg_form()
    else:
        form = reg_form(data=request.POST)

        if form.is_valid():
            new_user = form.save()
            login(request, new_user)
            return redirect('game:shop')

    context = {'title': 'YorsGate', 'form': form}
    return render(request, 'registration/register.html', context=context)

YorsGate/game/templates/game/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{{ title }}</title>
    <link type="text/css" href="{%  static 'game/css/style.css' %}" rel="stylesheet">
    <script type="text/javascript" src="{% static 'game/js/script.js' %}"></script>
</head>
<body>

<div class="wrapper">
    <!-- Main menu -->
{% block mainmenu %}

{% endblock mainmenu %}
<!-- End main menu -->

<div class="content">
    {% block content %}

{% endblock content %}
</div>

<!-- Footer -->
{% block footer %}
    <div class="footer">
        <p style="opacity: 1; color: azure">&copy; 2023 Zhurbenko Rostislav</p>
    </div>
{% endblock footer %}
<!-- End footer -->
</div>
</body>
</html>

YorsGate/game/templates/game/merchant.html
{% extends "game/base.html" %}

{% load game_tags %}


{% block mainmenu %}
    <div class="header">
        <p class="link-mainpage"><a href="{% url 'users:home' %}"><b>YorsGate</b></a></p>
        <ul class="menu-main">
            <li><a href="{% url 'game:order_page' %}" class="current">Порт</a></li>
            <li><a href="{% url 'game:warehouse' %}">Склад</a></li>
            <li><a href="{% url 'game:shop' %}">Магазин</a></li>
        </ul>
        <div class="money" >Золото:
            <input type="number" readonly value="{{ player.money }}" class="money_num" id="money_num">
        </div>
    </div>
{% endblock %}

{% block content %}
    <div class="block" id="about">
        <h1>Порт гордого міста Йорс</h1>
        <p>Сюди припливають найкращі заморські товари, тут ви можете зробити замовлення товарів</p>
    </div>
    <div class="block" id="queque">
        <h1>Дошка замовлень:</h1>
        <table>
        <tr><td><h3>Назва товару:</h3></td> <td><h3>Вага:</h3></td> <td><h3>Ціна:</h3></td> <td><h3>Додати:</h3></td><td><h3>Забрати:</h3></td><td><h3>Відмовитись</h3></td></tr>
            {% for ware in wares %}
                <tr>
                <td>{{ ware.product_name }} </td> <td>{{ ware.product_volume }}</td> <td>{{ ware.price }} золотих</td>
                <td><button class="button-buy plus" data-id="buy{{ ware.id }}">+</button></td>
                <td><button class="button-buy minus" data-id="buy{{ ware.id }}">-</button></td>
                <td><button class="button-buy cansel" data-id="buy{{ ware.id }}">Відмінити</button></td>
                </tr>
            {% endfor %}
        </table>

    </div>

    <div class="block" id="order">
        <div id="order_list">

        </div>
        <div class="accept">
            <label for="order_volume">Загальна вага:</label><input id="order_volume" readonly type="number" class="money_num">
            <label for="order_sum">Сума замовлення:</label><input id="order_sum" readonly type="number" class="money_num">
            <button class="button-buy buy">Замовити</button><button class="button-buy clear">Очистити</button>
        </div>
        <div id="info_block">

        </div>
    </div>
    <script>
    "use strict"
            let player_money = {{ player.money }};
            let player_volume = {{ player.warehouse_capacity }};
            let order_sum = 0;
            let order_volume = 0;

            let wareData = [
                {% for ware in wares %}
                    {
                        'id': 'buy{{ ware.id }}',
                        "name": '{{ ware.product_name }}',
                        'price': {{ ware.price }},
                        'volume': {{ ware.product_volume }},
                        'count': 0,
                        'ware': {{ ware.id }}
                    },
                {% endfor %}
            ]

            window.onload = function (){
                viewElements(wareData);
            }

            window.onclick = event => {
                if(event.target.classList.contains('plus')){
                    plusFunction(event.target.dataset.id);
                }
                if(event.target.classList.contains('minus'))
                {
                    minusFunction(event.target.dataset.id);
                }
                if(event.target.classList.contains('cansel'))
                {
                    canselFunction(event.target.dataset.id);
                }
                if(event.target.classList.contains('clear')){
                    clearFunction(wareData);
                }
                if(event.target.classList.contains('buy')){
                    if(order_sum >= player_money){
                        alertFunction(1);
                    }else if(order_volume >= player_volume){
                        alertFunction(2);
                    }
                    else{
                        sendFunction();
                        clearFunction(wareData);
                        alertFunction(0);
                        order_sum = 0;
                        order_volume = 0;
                        document.location.reload();
                    }
                }
                viewElements(wareData);
            }

            let alertFunction = typeAlert =>{
                let block = document.getElementById("info_block")
                switch (typeAlert){
                    case 0:
                        block.innerHTML = '<p>Замовлення успішне</p>'
                        break;
                    case 1:
                        block.innerHTML = '<p>!!!Недостатньо коштів!!!</p>'
                         break;
                    case 2:
                        block.innerHTML = '<p>!!!Недостатньо місця на складі!!!</p>'
                         break;
                }
            }

            async function request(url, data, csrftoken){
                const response = await fetch(url,{
                    method: 'POST',
                    headers: {
                        'Content-Type': 'application/x-www-form-urlencoded',
                        'X-CSRFToken': csrftoken,
                    },
                    body: JSON.stringify(data),
                });
                return await response.text();
            }

            async function sendFunction(){
                const url = '{% url 'game:warehouse' %}';
                const data = wareData;
                const csrftoken = '{{ csrf_token }}'
                const result = await request(url, data, csrftoken)
            }

            let canselFunction = id =>{
                wareData.forEach(element => {
                    if (element['id'] === id){
                        element['count'] = 0;
                    }
                })
            }

            let plusFunction = id =>{
                wareData.forEach(element => {
                    if (element['id'] === id){
                        element['count']++;
                    }
                })
            }

            let minusFunction = id =>{
                wareData.forEach(element => {
                    if (element['id'] === id && element['count'] > 0){
                        element['count']--;
                    }
                })
            }

            let clearFunction = () => {
                wareData.forEach(element =>
                {
                    element.count = 0;
                })
            }

            let viewElements = list => {
                let str = '<h1>Список замовлених товарів</h1><table>' +
                    '<td><h3>Назва:</h3></td> ' +
                    '<td><h3>Об`єм:</h3></td> ' +
                    '<td><h3>Ціна:</h3></td> ' +
                    '<td><h3>Кількість:</h3></td>';

                let volume = 0;
                let sum = 0;
                list.forEach(element => {
                    if (element.count > 0){
                        str += `<tr>
                        <td>${element.name}</td>
                        <td>${element.volume}</td>
                        <td>${element.price}</td>
                        <td>${element.count}</td>
                        </tr>`;

                        sum += element.price * element.count;
                        volume += element.volume * element.count;
                    }
                })
                str += '</table>';
                document.getElementById('order_list').innerHTML = str;
                document.getElementById('order_sum').value = sum;
                document.getElementById('order_volume').value = volume;
                order_sum = sum;
                order_volume = volume;
            }
        </script>
{% endblock %}

YorsGate/game/templates/game/shop.html
{% extends 'game/base.html' %}

{% block mainmenu %}
    <div class="header">
        <p class="link-mainpage"><a href="{% url 'users:home' %}"><b>YorsGate</b></a></p>
        <ul class="menu-main">
            <li><a href="{% url 'game:order_page' %}">Порт</a></li>
            <li><a href="{% url 'game:warehouse' %}">Склад</a></li>
            <li><a href="{% url 'game:shop' %}" class="current">Магазин</a></li>
        </ul>
        <div class="money">Золото:
            <input type="number" readonly value="{{ player.money }}" class="money_num">
        </div>
    </div>
{% endblock %}

{% block content %}
    <div class="block">
        <h1>Ваш маленький магазин</h1>
        <p>Тут ви можете продавати товари</p>
    </div>
    <div class="block">
    </div>
    <script>
    "use strict"

        let wareData = [
           {% for ware in player_wares %}
                {
                    'id': {{ ware.ware.id }},
                    'name': '{{ ware.ware.product_name }}',
                    'count': {{ ware.count }},
                    'price': {{ ware.ware.price }}
                },
            {% endfor %}
        ]

        window.onclick = event =>{

        }

        async function request(url, data, csrftoken){
                const response = await fetch(url,{
                    method: 'POST',
                    headers: {
                        'Content-Type': 'application/x-www-form-urlencoded',
                        'X-CSRFToken': csrftoken,
                    },
                    body: JSON.stringify(data),
                });
                return await response.text();
            }

        async function sendFunction(data){
                const url = '{% url 'game:shop' %}';
                const csrftoken = '{{ csrf_token }}'
                const result = await request(url, data, csrftoken)
            }
    </script>
{% endblock %}

YorsGate/game/templates/game/warehouse.html
{% extends 'game/base.html' %}

{% block mainmenu %}
     <div class="header">
        <p class="link-mainpage"><a href="{% url 'users:home' %}"><b>YorsGate</b></a></p>
        <ul class="menu-main">
            <li><a href="{% url 'game:order_page' %}" >Порт</a></li>
            <li><a href="{% url 'game:warehouse' %}" class="current">Склад</a></li>
            <li><a href="{% url 'game:shop' %}">Магазин</a></li>
        </ul>
        <div class="money" >Золото:
            <input type="number" readonly value="{{ player.money }}" class="money_num">
        </div>
    </div>
{% endblock %}

{% block content %}
    <div class="block" >
        <h1>Портовий склад</h1>
        <p>Величезна будівля, простора, тут зберігаються ваші товари</p>
    </div>
    <div class="block" id="ware_list">
    <h1>Список наявних товарів</h1>
        <table>
        <td><h3>Назва:</h3></td><td><h3>Об`єм:</h3></td><td><h3>Ціна:</h3></td><td><h3>Кількість:</h3></td>
        {% for ware in wares %}
            <tr>
                        <td>{{ ware.ware.product_name }}</td>
                        <td>{{ ware.ware.product_volume }}</td>
                        <td>{{ ware.ware.price }}</td>
                        <td>{{ ware.count }}</td>
            </tr>
        {% endfor %}
        </table>
        <p>--------------{{ wares_volume }}/{{ capacity }}--------------</p>
    </div>
    <script>



    </script>
{% endblock %}

YorsGate/users/templates/users/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{{ title }}</title>
    <link type="text/css" href="{%  static 'users/css/style.css' %}" rel="stylesheet">
</head>
<body>

<div class="wrapper">
    <!-- Main menu -->
{% block mainmenu %}
    <div class="header">
        <p class="link-mainpage"><a href="{% url 'users:home' %}">YorsGate</a></p>
    </div>
{% endblock mainmenu %}
<!-- End main menu -->

    <div class="content">
        <div class="about">
{% block content %}

{% endblock content %}
        </div>
    </div>

<!-- Footer -->
{% block footer %}
    <div class="footer">
        <p style="opacity: 1; color: azure">&copy; 2023 Zhurbenko Rostislav</p>
    </div>
{% endblock footer %}
<!-- End footer -->
</div>
</body>
</html>

YorsGate/users/templates/users/index.html
{% extends 'users/base.html' %}

{% block content %}
            <div class="caption">
                YorsGate
            </div>
            <div class="lore">
                Йорс старе портове місто де є купа героїв... Ви ж не герой... Ви той до кого герої приходять щоразу
            </div>
            <p class="butt_box">
            {% if user.is_authenticated %}
                <a href="{% url 'game:order_page' %}">Почати пригоду</a>
                <p class="butt_box">
                <a href="{% url 'users:logout' %}">Вийти</a>
                </p>
            {% else %}
                <a href="{%  url 'users:login' %}">Увійти</a>
            {% endif %}
            </p>
{% endblock content %}